// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usytqeyomlxtjuqzdruc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzeXRxZXlvbWx4dGp1cXpkcnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDQwMTcsImV4cCI6MjA3NDQyMDAxN30.IiTAJyUeOAjWgaI85WsiMTXty2VoxuPfOzK5o3qemKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});